### ISSUE TITLE
Blend MathJax display math background with theme

### ISSUE THREAD

**Issue by rbeezer** [sagemathinc/smc#136]
Discussion/request:

https://groups.google.com/forum/#!topic/sage-cloud/YaLP5hx416k

This will help, if not do the job.

```css
.MathJax_SVG_Display {background-color: inherit;}
```
